### PR TITLE
Please don't display passwords in the clear.

### PR DESCRIPTION
**Pull request by Hoverbear**
I really don't think it's a polite thing to display the users password in the clear on the login screen. Why not hide it with input types? If you'd like we can add in a toggle to show on demand.

### CODE REVIEW

**Comment by yuvipanda** [comment]
Also fixed in #9 :)

**Comment by yuvipanda** [comment]
And I don't think adding a toggle is even necessary. This isn't really targeted at mobile devices...

**Comment by Hoverbear** [comment]
Hah! You're right about #9! Didn't see that.

Alright, I agree.

**Comment by Hoverbear** [comment]
Is there any sort of confirmation when you're logged in?

**Comment by yuvipanda** [comment]
There isn't, and I think we should add one. Open a new issue / pull request for that?

**Comment by yuvipanda** [comment]
Do look at the rest of my pull requests though, might be useful! :)

**Comment by Hoverbear** [comment]
Yeah! Look before you leap! Hah.

**Comment by yuvipanda** [comment]
Now that #9 is merged, can you close this? :)

**Comment by AlexTatiyants** [comment]
Already done by #9, closing the issue

**Pull request closed without merging**
