### PR TITLE
Tolerate blog urls that do not have http in them

### LINKED ISSUE #10: Fails to connect to blog if blog url doesn't start with http://
Should either autodetect and add it, or validate more strictly.

### PR DESCRIPTION
**Pull request by yuvipanda**
Fixes #10

### CODE REVIEW

**Comment by yuvipanda** [comment]
Let me rebase and push again?

**Comment by yuvipanda** [comment]
Force pushed. Should not have changes to platen.js

**Comment by AlexTatiyants** [comment]
I'm having a hard time keeping up with you :)

**Comment by yuvipanda** [comment]
That's a good thing :D

**Comment by AlexTatiyants** [comment]
indeed!

**Pull request merged**
