### PR TITLE
Add WTFPL license

### LINKED ISSUE #13: Add a LICENSE file
To make it clear what the terms of this open source project are.

I'm personally a fan of the WTFPL.

### PR DESCRIPTION
**Pull request by yuvipanda**
Fixes #13.

Let me know if you prefer a different license :)

### CODE REVIEW

**Comment by AlexTatiyants** [comment]
As much as I love the frank nature of the WTFPL, I'd prefer something a bit less cursy :). Personally, I'm a fan of the MIT License.

**Comment by yuvipanda** [comment]
Hmm, mind if I add the Apache license? It retains the spirit of the MIT license, and is far more complete.

**Comment by AlexTatiyants** [comment]
Sure, that's fine. Thanks again for doing all this work, I really appreciate it!

**Comment by yuvipanda** [comment]
:D Not going to be the end of it! Do you hang out on IRC anywhere?

**Comment by AlexTatiyants** [comment]
Unfortunately I don't have an IRC account, though I do agree it may be helpful. I'll look into getting one.

**Comment by yuvipanda** [comment]
Any form of collaboration that's not just via issues and pull requests is fine :) And do get this merged too!

I'm looking at todo.txt, to see if there's anything else I could pick up on.

**Comment by AlexTatiyants** [comment]
Probably the most pressing piece of work is being able to download current posts from your WordPress blog. I looked into doing it, but converting from HTML to Markdown seemed like a bit of a PIA.

**Comment by yuvipanda** [comment]
Let me open a new issue to discuss that

**Comment by AlexTatiyants** [comment]
Cool. I'm going to sign off for now, but will look at this first thing tomorrow.

**Comment by artob** [comment]
For future needs, you might also want to consider the [Unlicense](http://unlicense.org) public domain dedication as a WTFPL alternative.

**Pull request merged**
